#  SPDX-License-Identifier: Apache-2.0
#
#  Copyright 2023-2026 The Konstraints Authors
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

[versions]
java-jdk = "11"
kotlin = "2.2.21"
prettier-toml = "2.0.1"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }
download = { id = "de.undercouch.download", version = "5.6.0" }
gitVersioning = { id = "me.qoomon.git-versioning", version = "6.4.4" }
kotlin-dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kover = { id = "org.jetbrains.kotlinx.kover", version = "0.8.3" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
node = { id = "com.github.node-gradle.node", version = "7.1.0" }
spotless = { id = "com.diffplug.spotless", version = "8.0.0" }
taskTree = { id = "com.dorongold.task-tree", version = "4.0.0" }
versions = { id = "com.github.ben-manes.versions", version = "0.51.0" }

[libraries]
junit-bom = { group = "org.junit", name = "junit-bom", version = "5.13.4" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" } # version from BOM
junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" } # version from BOM
konstraints = { group = "tools.aqua", name = "konstraints-all", version = "0.3-34-datatypes-support-39-943611e-SNAPSHOT" }
